spring:
  application:
    name: kd-ecommerce
  h2:
    console:
      enabled: true
      path: /h2-console # Console will be available at http://localhost:8080/h2-console
  datasource:
    url: jdbc:h2:mem:testdb # In-memory database named 'testdb'
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
    ddl-auto: update # Automatically creates/updates table schema based on entities
    show-sql: true # Log SQL queries to the console
  app:
    jwtSecret : mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs : 300000000000
    jwt:
      cookieName: kdEcomJwtCookie
project:
  image: uploads/
